name: Production Build resume.jesselawler.com

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Use the node version specified in the strategy
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2

      # Install packages
      - name: Install packages
        run: |
          yarn install

      # Build an optimized production build
      - name: Production build
        run: |
          unset CI
          yarn build

      # build an .env file from GitHub Secrets - see https://github.com/marketplace/actions/create-env-file
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          #envkey_DEBUG: false
          #envkey_SOME_API_KEY: "123456abcdef"
          envkey_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          #envkey_VARIABLE: ${{ vars.SOME_ACTION_VARIABLE }}
          #some_other_variable: foobar
          #directory: <directory_name>
          file_name: .env
          fail_on_empty: true
          sort_keys: false

      # Deploy to the S3 server
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"
